Algoritmo "exercicio 5"

Var
             xa,ya,xb,yb, resultado:real

Inicio
            escreva("escreva o valor de xa: ")
            leia(xa)
            escreva("escreva o valor de ya: ")
            leia(yb)
            escreva(" escreva o valor de xb: ")
            leia( xb)
            escreva("escreva o valor de yb: ")
            leia(yb)
            resultado<- raizq((xb-xa)^2+(yb-ya)^2))
            escreva("resultado da distancia: ",resultado)


Fimalgoritmo