Algoritmo "exercicio 2"

Var

      rendimento,altura,comprimento, resultado:real
      

Inicio
          escreva("digite o rendimento da tinta em litros/m^2: ")
          leia(rendimento)
          escreva("digite a altura do muro: ")
          leia(altura)
          escreva("digite o comprimento do muro: ")
          leia(comprimento)
          resultado<- altura*comprimento*rendimento
          escreva("a quantidade de tinta nescessaria em L será: ",resultado)


           

Fimalgoritmo